# Excercise on finding number of points outside n dimential sphere


In [0]:
import numpy as np

In [0]:
ndim = 2

In [0]:
npoints = 100000


In [0]:
points = np.random.rand(npoints,ndim)


In [0]:
points[0:2,:]


array([[0.07460343, 0.1412852 ],
       [0.20757094, 0.24214885]])

In [0]:
  dfo = np.zeros((npoints,1))

In [0]:
print(dfo)

[[0.]
 [0.]
 [0.]
 ...
 [0.]
 [0.]
 [0.]]


In [0]:
outside_points = 0

In [0]:
%%time
for i in range(npoints):
   for j in range(ndim):
     dfo[i] += points[i,j] ** 2
   dfo[i] = np.sqrt(dfo[i])
   if dfo[i] > 1:
        outside_points +=1


In [0]:
print('Fraction of points outside ',outside_points/npoints)

Fraction of points outside  0.2145313


In [0]:
# 1 - (pi/4)
1-3.14/4

0.21499999999999997

In [0]:
# instead of two for loops we can make use of built in functions of pi
%%time
sq_points = points * points
dfo = np.sqrt(np.sum(sq_points,axis=1))
outside_points = np.sum(dfo > 1)
print('Fraction of points outside ',outside_points/npoints)

Fraction of points outside  0.21509


In [0]:
%%time
outside_points = np.sum(np.sum(points * points,axis=1) > 1)

CPU times: user 3.13 ms, sys: 994 µs, total: 4.13 ms
Wall time: 3.44 ms


In [0]:
def area_outside_square(npoints,ndim):
    points = np.random.rand(npoints,ndim)
    return np.sum(np.sum(points * points,axis=1) > 1)/npoints

In [0]:
print('fraction of points for 3rd dim',area_outside_square(10000,2))

fraction of points for 3rd dim 0.2147


# Broadcasting


In [0]:
arr1 = np.arange(6)

In [0]:
arr1.shape

(6,)

# Reshaping the array



In [0]:
arr1 = arr1.reshape((3,2))

In [0]:
arr1

array([[0, 1, 2],
       [3, 4, 5]])

In [0]:
arr2 = np.arange(6).reshape((3,2))

In [0]:
arr1 + arr2

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]])

In [0]:
arr2[0].reshape((1,2))

array([[0, 1]])

In [0]:
arr1 + arr2[0].reshape((1,2))

array([[0, 2],
       [2, 4],
       [4, 6]])

In [0]:
arr1.T


array([[0, 2, 4],
       [1, 3, 5]])

# File handling

In [0]:
import numpy as np
planets_small = np.loadtxt('planets_small.txt',skiprows = 1,usecols=(1,2,3,4,5,6,7,8,9))

In [0]:
print(planets_small)

[[3.3000e-01 4.8700e+00 5.9700e+00 6.4200e-01 1.8980e+03 5.6800e+02
  8.6800e+01 1.0200e+02 1.4600e-02]
 [5.7900e+01 1.0820e+02 1.4960e+02 2.2790e+02 7.7860e+02 1.4335e+03
  2.8725e+03 4.4951e+03 5.9064e+03]
 [4.2226e+03 2.8020e+03 2.4000e+01 2.4700e+01 9.9000e+00 1.0700e+01
  1.7200e+01 1.6100e+01 1.5330e+02]]


In [0]:
planets_small.shape

(3, 9)

By default delimiter is space

In [0]:
planets = np.genfromtxt('planets_many.txt',skip_header = 1,usecols=(1,2,3,4,5,6,7,8,9))

In [0]:
print(planets)

In [0]:
planets.shape

(20, 9)

In [0]:
np.isnan(planets)

### convert nan into something

In [0]:
planets_new = np.nan_to_num(planets,nan=-1)

In [0]:
print(planets_new)

In [0]:
np.savetxt('planetsnew.txt',planets_new,delimiter=',')

In [0]:
np.save("planetsnew",planets_new)

In [0]:
!ls


planets-200320-181217.txt  planetsnew.txt		    sample_data
planets_many.txt	   planets_small-200320-181217.txt
planetsnew.npy		   planets_small.txt


In [0]:
!ls -lh

total 32K
-rw-r--r-- 1 root root 1.5K Apr 27 16:52 planets-200320-181217.txt
-rw-r--r-- 1 root root 1.5K Apr 27 16:57 planets_many.txt
-rw-r--r-- 1 root root 1.6K Apr 27 17:04 planetsnew.npy
-rw-r--r-- 1 root root 4.5K Apr 27 17:03 planetsnew.txt
-rw-r--r-- 1 root root  254 Apr 27 16:52 planets_small-200320-181217.txt
-rw-r--r-- 1 root root  254 Apr 27 16:54 planets_small.txt
drwxr-xr-x 1 root root 4.0K Apr  3 16:24 sample_data


In [0]:
np.savez('many_arrays',arr1,arr2,arr2.T)

In [0]:
arr = np.load('many_arrays.npz')
print(arr['arr_0'])

[[0 1]
 [2 3]
 [4 5]]


In [0]:
np.savez_compressed('many_arrays_compressed',arr1,arr2,arr2.T)

In [0]:
!ls -lh

In [0]:
arr0 = np.zeros((10000,10000))

In [0]:
np.savez('zeros',arr0)

In [0]:
np.savez_compressed('zeros_compressed',arr0)

In [0]:
!ls -lh | grep zeros

-rw-r--r-- 1 root root 760K Apr 27 17:14 zeros_compressed.npz
-rw-r--r-- 1 root root 763M Apr 27 17:14 zeros.npz


# Apply Statistical functions on Numpy

In [0]:
arr = np.random.rand(100000,)

In [0]:
np.amin(arr)

1.4785093628288948e-06

In [0]:
np.amax(arr)

0.9999944440770134

In [0]:
np.mean(arr)

0.5006758639052906

In [0]:
np.var(arr)

0.08324287777942112

In [0]:
np.std(arr)

0.28851841844052367

In [0]:
np.median(arr)

0.5013817731938435

In [0]:
np.percentile(arr,50)

0.5013817731938435

In [0]:
np.percentile(arr,10)

0.10062923301889312

In [0]:
np.percentile(arr,90)

0.900761718151148

In [0]:
np.percentile(arr,75)-np.percentile(arr,25)

0.49970522279255714

In [0]:
quartile = np.percentile(arr,[75,25])

In [0]:
print(quartile[0]-quartile[1])

0.49970522279255714


In [0]:
(arr-np.mean(arr))/np.std(arr)

array([ 0.90132395, -0.12163431, -0.92111599, ...,  1.08880684,
        1.08623044,  1.47049817])

In [0]:
np.histogram(arr,bins=5)

(array([19951, 19943, 19983, 20183, 19940]),
 array([5.99201590e-06, 2.00003682e-01, 4.00001373e-01, 5.99999063e-01,
        7.99996754e-01, 9.99994444e-01]))

In [0]:
arr

array([0.76072443, 0.46558213, 0.23491694, ..., 0.81481669, 0.81407335,
       0.92494167])

In [0]:
np.digitize(arr,bins=[1,2,3])

array([0, 0, 0, ..., 0, 0, 0])

In [0]:
arr1=np.random.randint(0,10,(10))
print(arr1)

[3 0 2 5 2 3 7 4 9 8]


In [0]:
np.digitize(arr1,bins=[0,5,10],right=True)

array([1, 0, 1, 1, 1, 1, 2, 1, 2, 2])

In [0]:
arr1= np.random.randint(50,80,100)

In [0]:
arr2= np.random.randint(150,185,100)

In [0]:
arr3=np.random.randint(17,22,100)

In [0]:
np.concatenate((arr1,arr2,arr3))

array([ 56,  70,  72,  59,  79,  51,  66,  52,  79,  60,  79,  75,  50,
        74,  69,  65,  73,  62,  57,  73,  65,  66,  71,  54,  77,  71,
        67,  79,  50,  54,  66,  53,  60,  52,  56,  78,  51,  75,  64,
        53,  63,  58,  64,  72,  71,  56,  66,  50,  75,  57,  51,  78,
        71,  74,  55,  76,  68,  57,  74,  69,  52,  69,  55,  79,  78,
        51,  62,  51,  65,  50,  54,  54,  58,  71,  53,  52,  56,  64,
        52,  71,  64,  79,  79,  62,  58,  58,  69,  54,  67,  62,  68,
        57,  52,  67,  72,  54,  53,  61,  69,  51, 158, 178, 154, 164,
       176, 181, 177, 163, 158, 172, 167, 164, 163, 176, 184, 156, 169,
       163, 173, 168, 160, 167, 182, 152, 168, 174, 151, 168, 158, 162,
       179, 173, 165, 174, 176, 171, 160, 155, 153, 174, 159, 164, 184,
       177, 168, 169, 183, 151, 169, 175, 182, 166, 183, 157, 177, 151,
       150, 169, 159, 172, 184, 152, 183, 181, 170, 162, 161, 163, 170,
       172, 175, 162, 167, 163, 174, 159, 156, 178, 183, 152, 17

Not right because we need 3*100 shape

In [0]:
arr2d = np.vstack((arr1,arr2,arr3))
print(arr2d)

[[ 56  70  72  59  79  51  66  52  79  60  79  75  50  74  69  65  73  62
   57  73  65  66  71  54  77  71  67  79  50  54  66  53  60  52  56  78
   51  75  64  53  63  58  64  72  71  56  66  50  75  57  51  78  71  74
   55  76  68  57  74  69  52  69  55  79  78  51  62  51  65  50  54  54
   58  71  53  52  56  64  52  71  64  79  79  62  58  58  69  54  67  62
   68  57  52  67  72  54  53  61  69  51]
 [158 178 154 164 176 181 177 163 158 172 167 164 163 176 184 156 169 163
  173 168 160 167 182 152 168 174 151 168 158 162 179 173 165 174 176 171
  160 155 153 174 159 164 184 177 168 169 183 151 169 175 182 166 183 157
  177 151 150 169 159 172 184 152 183 181 170 162 161 163 170 172 175 162
  167 163 174 159 156 178 183 152 179 159 153 167 160 165 173 170 160 172
  152 154 163 169 174 164 170 179 154 161]
 [ 19  18  21  17  20  20  21  19  21  21  19  21  17  21  19  18  19  20
   20  20  18  18  17  20  17  17  18  20  19  19  21  18  17  21  20  19
   19  18  17  21  21  18 

In [0]:
np.amin(arr2d)

17

In [0]:
np.amin(arr2d,axis=1 )

array([ 50, 150,  17])

# Checking stats rules with numpy


In [0]:
import numpy as np
arr = np.random.rand(1000)

In [0]:
mean = np.mean(arr)

In [0]:
arr1 = arr-mean

In [0]:
np.mean(arr1)

-4.39648317751562e-17

# Computing mean with smaller set of values

In [0]:
arr = np.random.rand(1000)

In [0]:
for k in range(1,50):
  arr1 = arr[0:k]
  print(k,np.mean(arr1))

In [0]:
np.cumsum?


# Effect of outliers on mean and median

In [0]:
arr = np.random.randint(1,100,100)

In [0]:
np.mean(arr)

48.25

In [0]:
np.median(arr)

46.5

In [0]:
arr = np.append(arr,[1000,2000])

In [0]:
np.mean(arr)

76.7156862745098

In [0]:
np.median(arr)

47.0

# Effect of scaling arrays on mean and median

In [0]:
arr = np.random.rand(100)

In [0]:
np.mean(arr)

0.5296761220892419

In [0]:
np.median(arr)

0.5564283189600674

In [0]:
arr1 = 2.5 * arr +0.65

In [0]:
print(np.mean(arr1))

1.9741903052231047


In [0]:
print(np.mean(2.5*arr+0.65),2.5*np.mean(arr)+0.65)

1.9741903052231047 1.9741903052231047


In [0]:
print(np.var(2.5*arr+0.65),2.5*2.5*np.var(arr))

0.45549261686998327 0.4554926168699834


In [0]:
print(np.std(2.5*arr+0.65),2.5*np.std(arr))

0.6749019312981578 0.6749019312981579


# Case study

In [0]:
!head cric_data.tsv


	Sachin Tendulkar	Rahul Dravid	India
0	100	78	342
1	11	62	191
2	8	85	252
3	71	24	307
4	104	17	229
5	18	104	246
6	8	76	226
7	86	74	288
8	12	60	216


1. Find mean,median,IQR for Sachin,Rahul, and India
2. Find the histogram of Sachin's scores with 10bins
3. Find mean of Sachin's scores grouped by 25 matches
4. Find mean of sachin's scores where he has a score a century
5. Find mean of Sachin's scores when Rahul has scored less than 10
6. Find mean for Sachin's scores based on which quartile India's score falls in
7.For every match find out who has scored - Sachin or Rahul
8. How many more runs does Sachin score on average after having scored x runs?


# Basic Excercises of numpy

# How can we insure that we always get the same random number

In [0]:
np.random.seed(5)

In [0]:
np.random.rand(1) # Run np.random.seed(5) to get always [0.22199317]

array([0.91861091])